### ISSUE TITLE
Automatically compute periodicity error

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svZeroDSolver#17]
It would be a great addition if we printed the periodicity error of the last cardiac cycle to give users an idea of how converged the solution is. For every boundary condition, we would need to calculate a time constant `τ=RC` and estimate the periodic error `ε_∞` [as in here](https://doi.org/10.1007/s10439-021-02796-x).

Once we have that, we could also leave the number of cardiac cycles open and let simulations run until reaching a user-defined periodic error `ε_∞`. I think this would generally increase our accuracy and also avoid unnecessarily many cardiac cycles.

**Comment by JonathanPham** [comment]
@mrp089 @menon-karthik 
1. Do we want to print out periodicity error for only models with RCR boundary conditions at all outlets or for all models (including models with coronary boundary conditions, mixed, etc.)?
2. For models with just resistor boundary conditions, would we just not print anything?

**Comment by mrp089** [comment]
Happy that you're looking into this, @JonathanPham!

1. Usually, RCR outlets have very similar time constants, so they converge at the same time. However, that's user-dependent, so it could make sense to calculate the maximum time constant and use that to determine a periodic state to be on the safe side.
2. With only resistances, I think two cardiac cycles should be fine.

In addition/instead of printing out an error, we could also define an input parameter with the error metric and the simulation terminates once it reaches that (instead of specifying the number of cardiac cycles).

**Comment by mrp089** [comment]
If you introduce printouts, be careful to not slow the simulation down. We currently don't have any printouts in the `Release` build (only in `Debug`).

**Comment by JonathanPham** [comment]
I think introducing an input parameter with the periodicity error sounds good. 

So, if both the periodicity error and the number of cardiac cycles are provided as inputs, should we terminate the simulation once the error level is achieved, even if the simulation has not run for the specified number of cycles yet?

What if the user wants to run their simulation for a specific number of cycles, instead of running until a certain error is achieved? Or should we just remove this capability?

**Comment by mrp089** [comment]
I'd say you can't input both, either one or the other, and throw a descriptive error if they're both given

**Comment by JonathanPham** [comment]
Sounds good!

**Comment by JonathanPham** [comment]
Just talked to @menon-karthik and we plan to incorporate this feature for all models, including models with non-RCR boundary conditions. 

For a given model, we will compute the periodicity error based on the RCR boundary conditions present in the model, but we will print out the error between the last two cardiac cycles at the end of the simulation if the model has non-RCR boundary conditions, since the RCR-based periodicity error does not guarantee the model will converge.

**Comment by JonathanPham** [comment]
Summary of my thoughts on how to tackle this issue, based on in-person conversation with @menon-karthik:

The goal is to give users the option to simulate an open-loop 0D model until it converges.

In the 0D solver input file, users must specify the number of cardiac cycles, $n$, they want to run (this parameter is `number_of_cardiac_cycles` in the code). They will also have the **option** to specify a target cycle-to-cycle error, $\epsilon_{target}$.

If only $n$ is specified, then we will just run the 0D simulation for $n$ cycles.

If $\epsilon_{target}$ is also prescribed, then we will take separate steps depending on whether or not the 0D model includes a RCR boundary condition.
1. _if the model **does not have any** RCR boundary conditions_: First, we will first run the 0D simulation for $n$ cycles. Then, for each cap (inlet or outlet), compute the cycle-to-cycle error, $\epsilon$, for both pressure and flow rate, where $\epsilon = \text{abs}\left(\frac{QOI_{n} - QOI_{n-1}}{QOI_{n-1}}\right)$, where $QOI$ is a **mean** quantity of interest. If $\epsilon \leq \epsilon_{target}$ for **all** caps (for **both** pressure and flow rate), then the model has converged periodically and we can stop. Otherwise, the model has not converged. In this case, run another cardiac cycle, recompute $\epsilon$, and iterate until convergence.
2. _if the model **has only one** RCR boundary condition:_ For the outlet with the RCR boundary condition, evaluate equation 21 from [here](https://link.springer.com/article/10.1007/s10439-021-02796-x) to compute an estimated number of cardiac cycles, $n_{\infty}$. (Note that $n_{\infty}$ approximates that number of cardiac cycles that must be simulated in order to achieve a prescribed periodicity error, $\epsilon_{\infty}$. Also, for simplicity, we will assume $\epsilon_{\infty}$ matches $\epsilon_{target}$ in equation 21.) Run the 0D model for $n_{\infty}$ cycles, instead of $n$ cycles. Then, for all caps, compute $\epsilon$ for both pressure and flow rate and print them. No need to run for more cycles if the model has not converged, i.e., $\epsilon \> \epsilon_{target}$. Note that this model is required to have only one RCR boundary condition, but it can have other boundary conditions as well.
3. _if the model **has multiple** RCR boundary conditions_: Perform step 2 (above), but for the RCR boundary condition with the largest time constant, $\tau = R_{d}C$.

We will also create a new test case for each case above.
1. _if the model **does not have any** RCR boundary conditions_: Create a model based on `pulsatileFlow_R_coronary.json`, where we will output results at all time steps. Then, simulate the 0D model, compute the mean flow and pressure for the last two cardiac cycles simulated, and confirm that $\epsilon \leq \epsilon_{target}$.
2. _if the model **has only one** RCR boundary condition_ AND _if the model **has multiple** RCR boundary conditions_: Create a model based on `steadyFlow_bifurcationR_R2.json`, where we will output results at all time steps and the two RCR boundary conditions will have different time constants. Also, use a periodic inflow instead of a steady inflow. Compute $n_{\infty}$ per equation 21 of the paper, using the largest RCR time constant. Set `number_of_cardiac_cycles` to be a value that is different from $n_{\infty}$. Then, simulate the 0D model and confirm that the results have $n_{\infty}$ cycles instead of the value specified for `number_of_cardiac_cycles`.

**Comment by JonathanPham** [comment]
Added commit c480e45 to address the case 1 above (if the model does not have any RCR boundary conditions)

**Comment by JonathanPham** [comment]
Added commit 442caba to address cases 2 and 3 above (if the model has only one or multiple RCR boundary conditions)
