### ISSUE TITLE
Move svZeroDPlus to Simvascular and archive Simvascular/svZeroDSolver

### ISSUE THREAD

**Issue by menon-karthik** [SimVascular/svZeroDSolver#35]
### **This issue is a follow-up to #28 and the final step in making svZeroDPlus official.** 

_Below is a copy of the initial code and docs review by @ktbolt, copied over from #28._ 

 I had a look at some of the code and documentation, comments below.

**Documentation Review**

The `README` documentation needs to be improved 
- stating what is created when building: library and two executables
- a section describing the 3D solver interface

I can do this.

The `C++ Documentation` https://stanfordcbcl.github.io/svZeroDPlus/cpp/ needs to be improved 
- discusses Python
- can be organized a bit better

I can do this.

The documentation describing governing equations, code functionality, JSON file format, Python API, etc. needs to be in the SimVascular web site [here](https://simvascular.github.io/documentation/rom_simulation.html#0d-solver) not in github.io.

`Developer Guide` documentation is just a short _Architecture_ paragraph. There needs to be a _Design_ section that describes the problem, its components (i.e., objects) and how it is solved. Define any terms that will be used to relate the classes created in the implementation. 

There needs to be an _Implementation_ section that describes how the concepts in the `Design` section are realized in code. Describe the system structure (classes) and behavior, showing how the primary classes interact. Have a section describing how a developer can add new functionality.

`Code Comments`  
- some code (bloodvesseljunction.hpp) document equations which are not unreadable and essentially meaningless when a developer is looking in the source file. This kind of thing should be in the documentation. 
- don't need to add comments that are totally obvious (@brief Destroy the Block object)
- have comments of class method declaration rather than implementation

**Code Review**
I have identified a lot of issues in the code that need to be addressed. 

The primary issue (so far) in the implementation is the use of templates to define class float or double precision. There is no strong use-case for this and it makes the code cluttered and more complicated. So the first change to make is to remove all of the class templates and just use double.

I will list the other issues here after I finish my review of the code.

_Originally posted by @ktbolt in https://github.com/StanfordCBCL/svZeroDPlus/issues/28#issuecomment-1703950030_

**Comment by ktbolt** [comment]
I will open Issues for documentation and code changes. Comments on all Issues are welcome!

**Comment by mrp089** [comment]
Daniele extensively used the `0D+` solver to train a surrogate model for UQ in an upcoming paper (@richterjakob and I are co-authors). He just told me he wants to put the paper on arXiv by the end of the week. Since it's referenced in the paper, it would be great if `0D+` would be at a "more permanent place" by then.

@ktbolt, do you think we can move this repository to SimVascular by the end of this week? I'm happy to help wherever if you tell me where we need more work! Of course, we can keep restructuring the code after the move.

**Comment by ktbolt** [comment]
@mrp089 Let's plan on moving svZeroDPlus over by the end of the week. The major restructuring of the code is complete I think, I can continue to clean up the code and improve the documentation after it is moved. 

There are a few tasks that need to be done before we can move it I think
1) Build an installer using CPack
2) Modify SimVascular to execute a binary rather than a Python script
3) Modify SimVascular CMake file to not pull svZeroDSolver 
4) Update the SimTK svZeroDSolver information
5) Update GitHub Actions to build installers

Tasks 3-5 are pretty straightforward I think. 

Tasks 1) and 2) will require some effort so I could use some help on either. Do you have a preference?

**Comment by mrp089** [comment]
@ktbolt, excellent overview!

I can do 1), and I think it goes hand-in-hand with 5). I have no idea how to do 2).

**Comment by mrp089** [comment]
Actually, do we need `cpack` and an executable for SimVascular at all?

Can't we just run
```
pip install git+https://github.com/StanfordCBCL/svZeroDPlus.git
```
in SimVascular and execute simulations via the Python interface?

Same for installing `0D+` on users' machines: I think everybody has a Python setup and uses pip. For users that's also easier to keep track of than manually downloading installers and then running a program.

**Comment by mrp089** [comment]
Added installers in #51, built within GitHub actions.

**Comment by ktbolt** [comment]
A good start for the installer!

```
$ ls /usr/local/sv/svZeroDPlus/2023-10-11
bin/		include/	share/
```

A couple of comments
- We don't need the `share` and `include` directories
- We do need a `lib` directory containing the `libsvzero_interface.dylib` interface shared library

**Comment by mrp089** [comment]
@ktbolt, are we ready for the move?

**Comment by ktbolt** [comment]
@mrp089 I think we need to address https://github.com/StanfordCBCL/svZeroDPlus/issues/70 before we move.

**Comment by menon-karthik** [comment]
I am also going to work on #46 and #58 in anticipation of moving this over.

**Comment by mrp089** [comment]
One month and a couple of pull requests later - are we ready for the move?

**Comment by mrp089** [comment]
👍 I'll let @menon-karthik do the honors. And then we should have ourselves a release party!

**Comment by menon-karthik** [comment]
@ktbolt Thoughts on changing the name to svZeroD (the plus is silly for anyone outside the lab) either before or after moving the repository (or never)?

**Comment by ktbolt** [comment]
@menon-karthik I think it should be called `svZeroDSolver` since it is replacing that guy. 

We will need to build installers for it.

And I will need to change the SImTK downloads for svZeroDSolver.

**Comment by mrp089** [comment]
We were thinking `svZeroD` since it now has a solver and a calibrator. The two executables are `svzerodcalibrator` and `svzerodsolver`. And less to type is always good!

Installers are [here](https://github.com/StanfordCBCL/svZeroDPlus/actions/runs/7130774457) (the latest commit). They will also be visible once we create a new release [here](https://github.com/StanfordCBCL/svZeroDPlus/releases). We should follow [this guide](https://py-pkgs.org/07-releasing-versioning.html) for versioning, which will make it easier to publish it on PyPi later. So we could create release `2.0` after the move.

The current SimTK svZeroDSolver download section just contains a link to GitHub. If we point it [here](https://github.com/StanfordCBCL/svZeroDPlus/releases), users will always see the latest binaries on top, and we don't need to keep updating any links. The number of downloads can be [tracked](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-single-release) as well.

The `cpack` [install prefix](https://github.com/StanfordCBCL/svZeroDPlus/blob/master/distribution/CMakeLists.txt) can stay at `/usr/local/sv/ZeroDSolver/` since that's only the solver part.

**Comment by ktbolt** [comment]
I would like to just replace the current `svZeroDSolver`, keep the same name, document what it does on SimTK.

I'm not sure about just having links to installers, other applications don't have that, maybe have the installer and a link.
